---
name: Basic CI Checks

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y yamllint shellcheck

      - name: Check YAML files
        run: |
          yamllint .

      - name: Check shell scripts
        run: |
          shellcheck $(find . -type f -name "*.sh") || true

